name: ActionLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: "Quality analysis"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Set up JDK 21
      uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4.1.0
      with:
        java-version: '21'
        distribution: 'temurin'

    - uses: devops-actions/actionlint@v0.1.2
      continue-on-error: true
      id: action-lint
      
    - name: "Upload Artifact"
      uses: actions/upload-artifact@v4.3.1
      with:
        name: actionlint-results
        path: ${{ steps.action-lint.outputs.results-file }}
    
    
